//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGOUnnati.DALEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public byte UserRole { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> PermanentAddress { get; set; }
        public Nullable<int> CorrespondenceAddress { get; set; }
        public string EmailID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual UserRole UserRole1 { get; set; }
    }
}
